apiVersion: v1
kind: Service
metadata:
  name: flight-app
  namespace: flight-app
spec:
  selector:
    app: flight-app
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer
  externalIPs: 
  - 192.168.49.2