name: Release - Build & push

on:
  push:
  #  branches:
     # - 'develop'

jobs:
  
  docker:
    name: Build and Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker image build -t flight_delay_pred_app:v1 . 
             
      - name: Tag Docker image
        run: docker tag flight_delay_pred_app:v1 ${{ secrets.REPO }} 
      - name: Publish Docker image
        run: docker push ${{ secrets.REPO }} 
